# -*- coding: utf-8 -*-
"""abishek trinning .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FW3vBz_sk3L_F9BO-hp1jR0-Fuk2THcG
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()

file_name = list(uploaded.keys())[0]

df = pd.read_excel(file_name)

print("Dataset loaded successfully!")

print("First 5 rows:")
display(df.head())

print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

print("Column Names:")
print(df.columns.tolist())

print("Data Types:")
print(df.dtypes)

print("Missing Values:")
print(df.isnull().sum())

print("Number of Duplicate Rows:")
print(df.duplicated().sum())

print("Statistical Summary:")
display(df.describe())

print("Degree-wise Count:")
print(df["DEGREE"].value_counts())

print("Semester-wise Count:")
print(df["Sem"].value_counts().sort_index())

print("Result-wise Count:")
print(df["RESULT"].value_counts())

print("Average Internal Mark:", df["INT_MARK"].mean())
print("Average External Mark:", df["EXT_MARK"].mean())
print("Average Total Mark:", df["TOTAL_MARK"].mean())

print("Minimum Total Mark:", df["TOTAL_MARK"].min())
print("Maximum Total Mark:", df["TOTAL_MARK"].max())

plt.figure(figsize=(8,5))

sns.countplot(data=df, x="RESULT")

plt.title("Result Distribution")
plt.xlabel("Result")
plt.ylabel("Number of Students")
plt.xticks(rotation=45)

plt.show()

plt.figure(figsize=(8,5))

sns.histplot(df["TOTAL_MARK"], kde=True)

plt.title("Distribution of Total Marks")
plt.xlabel("Total Marks")
plt.ylabel("Frequency")

plt.show()

degree_marks = df.groupby("DEGREE")["TOTAL_MARK"].mean()

plt.figure(figsize=(10,5))

degree_marks.plot(kind="bar")

plt.title("Average Total Marks by Degree")
plt.xlabel("Degree")
plt.ylabel("Average Total Marks")
plt.xticks(rotation=45)

plt.show()

numeric_data = df.select_dtypes(include=np.number)

plt.figure(figsize=(10,7))

sns.heatmap(
    numeric_data.corr(),
    annot=True,
    cmap="coolwarm"
)

plt.title("Correlation Heatmap")

plt.show()

degree_count = df["DEGREE"].value_counts()

print(degree_count)

plt.figure(figsize=(10,5))
degree_count.plot(kind="bar")
plt.title("Number of Students by Degree")
plt.xlabel("Degree")
plt.ylabel("Number of Students")
plt.show()

semester_count = df["Sem"].value_counts().sort_index()

print(semester_count)

plt.figure(figsize=(8,5))
semester_count.plot(kind="bar")
plt.title("Number of Students by Semester")
plt.xlabel("Semester")
plt.ylabel("Number of Students")
plt.show()

plt.figure(figsize=(8,5))

sns.histplot(df["INT_MARK"], bins=20, kde=True)

plt.title("Internal Marks Distribution")
plt.xlabel("Internal Marks")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize=(8,5))

sns.histplot(df["EXT_MARK"], bins=20, kde=True)

plt.title("External Marks Distribution")
plt.xlabel("External Marks")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize=(8,5))

sns.histplot(df["TOTAL_MARK"], bins=20, kde=True)

plt.title("Total Marks Distribution")
plt.xlabel("Total Marks")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize=(8,4))

sns.boxplot(x=df["INT_MARK"])

plt.title("Internal Marks Boxplot")
plt.xlabel("Internal Marks")
plt.show()

!pip install streamlit openpyxl pandas

regon = "19UCH4725"
dob= pd.to_datetime("2002-09-18")

student=df[
 (df["REG_NO"]==regon)&(df["DOB"]==dob)]
print(student)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# st.title('My First Streamlit App')
# st.write('Hello, Streamlit!')
# 
# from google.colab import files
# 
# files.download('app.py')

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# streamlit
# openpyxl
# pandas
# 
# files.download("requirements.txt")

files.download(
    "199-LOYOLA COLLEGE OF ARTS & SCIENCE (Co.Ed), OILP.xlsx"
)

